# Generated by Django 4.2 on 2025-10-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id_business', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email_business', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=8)),
                ('description', models.TextField()),
                ('img_business', models.ImageField(upload_to='business/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProductModel',
            fields=[
                ('id_category_product', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
                ('img_product', models.ImageField(upload_to='product/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('tags', models.CharField(choices=[('OFR', 'Oferta'), ('NEW', 'Nuevo'), ('POP', 'Popular')], max_length=3)),
                ('moneda', models.CharField(choices=[('CUP', 'Moneda Nacional Cubana'), ('MLC', 'Dolar Americano Transferencia'), ('ZEL', 'Dolar Americano')], max_length=3)),
                ('id_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.businessmodel')),
                ('id_category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.categoryproductmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBusinessModel',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('id_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.businessmodel')),
            ],
        ),
    ]
