# Generated by Django 4.2 on 2025-10-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryproductmodel',
            old_name='name',
            new_name='category_name',
        ),
    ]
