# Generated by Django 5.2.7 on 2025-10-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_rename_name_categoryproductmodel_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorybusinessmodel',
            old_name='id_category',
            new_name='id_category_business',
        ),
    ]
