# Generated by Django 5.2.7 on 2025-10-10 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_rename_id_category_categorybusinessmodel_id_category_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='id_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='store_app.businessmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='id_category_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='store_app.categoryproductmodel'),
        ),
    ]
