# Generated by Django 5.2.7 on 2025-10-10 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_alter_productmodel_id_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='id_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.businessmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='id_category_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store_app.categoryproductmodel'),
        ),
    ]
