# Generated by Django 5.2.7 on 2025-11-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_alter_productmodel_id_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='eslogan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
