# Generated by Django 5.2.7 on 2025-12-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_businessmodel_eslogan_alter_businessmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='moneda',
            field=models.CharField(choices=[('CUP', 'Moneda Nacional Cubana'), ('MLC', 'Dolar Americano Transferencia'), ('ZELL', 'Dolar Americano')], max_length=4),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tags',
            field=models.CharField(choices=[('OFFER', 'Oferta'), ('NEW', 'Nuevo'), ('POPULAR', 'Popular')], max_length=7),
        ),
    ]
