# Generated by Django 5.2.7 on 2025-12-29 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_alter_productmodel_moneda_alter_productmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproductmodel',
            name='id_business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='store_app.businessmodel'),
            preserve_default=False,
        ),
    ]
