# Generated by Django 5.2.7 on 2025-12-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_accountmodel_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
