# Generated by Django 4.2 on 2025-10-05 15:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('PEN', 'Pendiente'), ('SEC', 'Realizado con exito'), ('ERR', 'Error en el pago')], max_length=3)),
                ('payment_method', models.CharField(choices=[('TRA', 'Transferencia'), ('CAS', 'Efectivo'), ('TRF', 'Transferencia desde el extranjero')], max_length=3)),
                ('created_at', models.DateField(auto_now=True)),
                ('completed_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type', models.CharField(choices=[('TE', 'Prueba Gratis'), ('MO', 'Mensual'), ('AN', 'Anual')], max_length=3)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id_subscription', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PEN', 'Pendiente'), ('CAN', 'Cancelada'), ('ACT', 'Activa'), ('DEF', 'Vencida')], max_length=3)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('id_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_app.paymentmodel')),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_app.planmodel')),
            ],
        ),
    ]
